Fixed return code of initd shell script

diff --git a/templates/serf_init.sh.j2 b/templates/serf_init.sh.j2
--- a/templates/serf_init.sh.j2
+++ b/templates/serf_init.sh.j2
@@ -33,7 +33,7 @@ start() {
         #Start quite background uid and gid
 		start-stop-daemon --start --quiet --background --name $NAME --chdir $BASE_DIR --chuid $RUN_AS_USER --group $RUN_AS_GROUP --exec $ExecFile
 
-		[ "$?" -ne 0 ] && echo "[ FAILED ]" && return 1
+		[ "$?" -ne 0 ] && echo "[ FAILED ]" && exit 1
 		let kwait=$SLEEP_FOR
 		count=0;
 		until [ $count -gt $kwait ]
@@ -45,10 +45,10 @@ start() {
 		PID=$(JAVA_PID)
 		if [ -n "$PID" ]; then
 			echo "[ OK ]"
-			return 0
+			exit 0
 		else
 			echo "[ FAILED ]"
-			return 1
+			exit 1
 		fi
 	fi
 }
@@ -58,7 +58,7 @@ stop() {
 	if [ -n "$PID" ]; then
 	    echo -n  "Stoping $NAME "
 		kill -9 $PID
-		[ "$?" -ne 0 ] && echo "[ FAILED ]" && return 1
+		[ "$?" -ne 0 ] && echo "[ FAILED ]" && exit 1
 
 		let kwait=$SLEEP_FOR
 	    count=0;
@@ -71,10 +71,10 @@ stop() {
     	PID=$(JAVA_PID)
 		if [ -n "$PID" ]; then
 			echo "[ FAILED ]"
-			return 1
+			exit 1
 		else
 			echo "[ OK ]"
-			return 1
+			exit 0
 		fi
 	else
         echo "$NAME not running."
@@ -95,7 +95,7 @@ reload() {
 	if [ -n "$PID" ]; then
 	    echo -n  "Reloading $NAME "
 		kill -HUP $PID
-		[ "$?" -ne 0 ] && echo "[ FAILED ]" && return 1
+		[ "$?" -ne 0 ] && echo "[ FAILED ]" && exit 1
 
 		let kwait=$SLEEP_FOR
 	    count=0;
@@ -108,10 +108,10 @@ reload() {
     	PID=$(JAVA_PID)
 		if [ -n "$PID" ]; then
 			echo "[ FAILED ]"
-			return 1
+			exit 1
 		else
 			echo "[ OK ]"
-			return 1
+			exit 1
 		fi
 	else
         start 
